### ISSUE TITLE
error message is not readable

### ISSUE THREAD

**Issue by srinivas3120** [oliviergauthier/gradle-appcenter-plugin#39]
com.betomorrow.gradle.appcenter.infra.AppCenterUploaderException: Can't prepare release upload, code=401, reason={"message":"9c103022-b3ce-41f7-b45c-de9ee51b72a1","statusCode":401,"code":"Unauthorized"}

whats the meaning of ``"message":"9c103022-b3ce-41f7-b45c-de9ee51b72a1"`` here ?

**Comment by oliviergauthier** [comment]
i think it's due to your token. maybe it has no write access or the user account that has generated the token has no write access for this appcenter app

**Comment by srinivas3120** [comment]
this message gets changed on every execution for the same uploadTask. 
is it encrypted, how do i read the message?

**Comment by oliviergauthier** [comment]
Actually, all `{"message":"9c103022-b3ce-41f7-b45c-de9ee51b72a1","statusCode":401,"code":"Unauthorized"}` is the response body returned from AppCenter API when we try to prepare the release. `9c103022-b3ce-41f7-b45c-de9ee51b72a1` is probably an http requestId. The important part of the message is the http status code `401` which mean that you are not allowed to request the API. This is probably due to you token that is not valid

**Comment by srinivas-mudavath** [comment]
may be its requestId, it's coming from app center api. 
i would have been nice if appcenter added a more meaningful message. Thank you.

closing this.

**Comment by srinivas3120** [comment]
may be its requestId, it's coming from app center api.
i would have been nice if appcenter added a more meaningful message. Thank you.

closing this.
